package com.qin.dao;

import com.qin.pojo.Post;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_post
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_post
     *
     * @mbg.generated
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_post
     *
     * @mbg.generated
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_post
     *
     * @mbg.generated
     */
    List<Post> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Post record);

    /**
     * 检索发布信息
     * */
    List<Post> retrieve(@Param("categoryId")Integer categoryId, @Param("time")Date time, @Param("address") String address,@Param("LoF") Integer LoF,@Param("keyword") String keyword);


}