package com.qin.dao;

import com.qin.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laf_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(@Param("userInfo") UserInfo userInfo);

    /**
     * 判断用户名是否存在
     * */
    Integer findByUsername(@Param("username")String username);

    /**
     * 根据用户名和密码查询用户
     * */
    UserInfo findByUsernameAndPassword(@Param("username")String username,@Param("password")String password);

}