package com.qin.pojo;

public class Carousel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laf_carousel.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laf_carousel.post_id
     *
     * @mbg.generated
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column laf_carousel.order
     *
     * @mbg.generated
     */
    private Integer order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laf_carousel.id
     *
     * @return the value of laf_carousel.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laf_carousel.id
     *
     * @param id the value for laf_carousel.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laf_carousel.post_id
     *
     * @return the value of laf_carousel.post_id
     *
     * @mbg.generated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laf_carousel.post_id
     *
     * @param postId the value for laf_carousel.post_id
     *
     * @mbg.generated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column laf_carousel.order
     *
     * @return the value of laf_carousel.order
     *
     * @mbg.generated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column laf_carousel.order
     *
     * @param order the value for laf_carousel.order
     *
     * @mbg.generated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }
}